spring.application.name=Banking_Management_System

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

server.servlet.context-path=/bms
server.port=4041


spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=asef
spring.datasource.password=shaikh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
